# Generated by Django 4.1.7 on 2023-05-10 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('interest_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('kms_driven', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15, null=True, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ('username',),
            },
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15, null=True, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staffs',
                'ordering': ('staffname',),
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('exshowroomprice', models.DecimalField(decimal_places=2, default=True, max_digits=10)),
                ('fuelfuelcapacity', models.CharField(blank=True, max_length=200)),
                ('fueltype', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='product')),
                ('banner', models.ImageField(blank=True, upload_to='product')),
                ('feature1', models.CharField(blank=True, max_length=200)),
                ('feature2', models.CharField(blank=True, max_length=200)),
                ('feature3', models.CharField(blank=True, max_length=200)),
                ('feature4', models.CharField(blank=True, max_length=200)),
                ('feature5', models.CharField(blank=True, max_length=200)),
                ('feature6', models.CharField(blank=True, max_length=200)),
                ('brochure', models.FileField(blank=True, upload_to='product')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='test_drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=100, null=True)),
                ('carmodel', models.CharField(max_length=100, null=True)),
                ('Contact', models.BigIntegerField(default=0)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('testdate', models.DateField(null=True)),
                ('testtime', models.TimeField(blank=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customername', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'test_drive',
                'verbose_name_plural': 'test_drive',
                'ordering': ('carmodel',),
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.customer')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.staff')),
            ],
            options={
                'verbose_name_plural': 'Staff Assignments',
            },
        ),
        migrations.CreateModel(
            name='showroom_visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carmodel', models.CharField(max_length=100, null=True)),
                ('Contact', models.BigIntegerField(default=0)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('visitdate', models.DateField(null=True)),
                ('visittime', models.TimeField(blank=True, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitername', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'showroom_visit',
                'verbose_name_plural': 'showroom_visit',
                'ordering': ('carmodel',),
            },
        ),
        migrations.CreateModel(
            name='Productgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='products')),
                ('feature', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='carapp.vehicles')),
            ],
            options={
                'verbose_name': 'Product Gallery',
                'verbose_name_plural': 'Product gallery',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_status', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CarLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField()),
                ('loan_tenure', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('emi_amount', models.FloatField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
